### ISSUE TITLE
Load HMDB data for protein-associated metabolites

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#110]
"The Human Metabolome Database (HMDB) is a freely available electronic database containing detailed information about small molecule metabolites found in the human body" (from https://hmdb.ca/). HMDB contains links between proteins and the metabolites they are associated with.  For example, the HMDB record for Homogentisate 1,2-dioxygenase ([UniProtKB:Q93099](https://www.uniprot.org/uniprot/Q93099)) is [HMDBP00842](https://hmdb.ca/proteins/HMDBP00842), and https://hmdb.ca/proteins/HMDBP00842/metabolite_protein_links shows the metabolites associated with this protein.  These relationships can also be downloaded from the [HMDB downloads page](https://hmdb.ca/downloads), and specifically the ["All proteins" file](https://hmdb.ca/system/downloads/current/hmdb_proteins.zip).  

This issue tracks the loading of these protein-associated metabolites to mygene.info.

Related to https://github.com/NCATSTranslator/testing/issues/49

**Comment by andrewsu** [comment]
Let's create this as a standalone "pending" API for now.  Also, let's create this as an "association"-style API, where each document describes a triple (subject/object/predicate).  This aligns with how we structured the semmeddb API described in this comment https://github.com/biothings/pending.api/issues/30#issuecomment-904319224.

**Comment by NikkiBytes** [comment]
Working example of the association structure for metabolite HMDB data below...

For an example of the data file and one protein, see [here](https://github.com/NikkiBytes/BioThings_dojo/blob/main/data_plugins/hmdb_proteins/proteins.xml). This is what I am currently extracting from to get the structure below. 
  
The protein data is in a nested `.xml` file. and the association ids are found under the `metabolite_reference` tag , and the `metabolite_associations` tag. The former contains a reference to the `pmid`, while `metabolite_associations` only contains id and name. 

Currently I am adding the `metabolite_associations` data. 

Below is a clean working version of the association structure of the `metabolite_reference` data.  

I hope this is clear. @colleenXu and @newgene , if you could view the structure below and let me know if there are any details to modify or add.
For all data from the file, preview the [data file example](https://github.com/NikkiBytes/BioThings_dojo/blob/main/data_plugins/hmdb_proteins/proteins.xml) .

As well, @andrewsu mentioned the HMDB ID for metabolites might not be used within Translator and that since HMDB has already done mappings to other database identifiers (e.g., https://hmdb.ca/metabolites/HMDB0015122#links), **I should include those in the object dict.**  These links are not in the proteins file, so I am looking for a file to extract those from.  
```
[
    {
        "_id": "HMDBP00001_1",
        "predicate": "biolink:related_to",
        "pmid": "11752352",
        "subject": {
            "uniprot_id": "P21589",
            "uniprot_name": "5NTD_HUMAN",
            "genbank_protein_id": "23897",
            "hgnc_id": "HGNC:8021",
            "genbank_gene_id": "X55740",
            "gene_name": "NT5E"
        },
        "object": {
            "name": "Pentoxifylline",
            "accession": "HMDB0014944"
        }
    },
    {
        "_id": "HMDBP00001_2",
        "predicate": "biolink:related_to",
        "pmid": "16426349",
        "subject": {
            "uniprot_id": "P21589",
            "uniprot_name": "5NTD_HUMAN",
            "genbank_protein_id": "23897",
            "hgnc_id": "HGNC:8021",
            "genbank_gene_id": "X55740",
            "gene_name": "NT5E"
        },
        "object": {
            "name": "Pentoxifylline",
            "accession": "HMDB0014944"
        }
    },
    {
        "_id": "HMDBP00001_3",
        "predicate": "biolink:related_to",
        "pmid": "19842938",
        "subject": {
            "uniprot_id": "P21589",
            "uniprot_name": "5NTD_HUMAN",
            "genbank_protein_id": "23897",
            "hgnc_id": "HGNC:8021",
            "genbank_gene_id": "X55740",
            "gene_name": "NT5E"
        },
        "object": {
            "name": "Cytarabine",
            "accession": "HMDB0015122"
        }
    }
]
```

**Comment by colleenXu** [comment]
@andrewsu @NikkiBytes  A few questions after looking over the [XML example](https://github.com/NikkiBytes/BioThings_dojo/blob/main/data_plugins/hmdb_proteins/proteins.xml) vs the [website](https://hmdb.ca/proteins/HMDBP00001): 

* I think the type of protein (it's under <protein_type>) could be included. Perhaps it would be helpful for deciding what kind of association this is. I think possible values are "enzyme",  "transporter", "cofactor", and "unknown" but I'm not sure
* do we want to use biolink predicates here? It feels like that's inserting info that's not in the original data
* the [website](https://hmdb.ca/proteins/HMDBP00001) seems to have info on reactions that the protein catalyzes, which shows metabolites as input or outputs. I don't see it in the [XML example](https://github.com/NikkiBytes/BioThings_dojo/blob/main/data_plugins/hmdb_proteins/proteins.xml) for some reason...perhaps having that info would be nice because it might allow for a more specific metabolite-protein relationship for each pair...

**Comment by andrewsu** [comment]
A few followups to @colleenXu's reply, hitting the bullet points in order:

* sure, if protein type is easily added under `subject.protein_type`, sounds good.  I don't see an immediate application of this so not the highest priority if not.
* right, great point.  We will add that in the smartAPI record, so let's remove `predicate`
* hmm, agreed, links to specific reactions would be great.  I'm not seeing a place where they would live in any of the other downloadable files, so I'm guessing they are excluding this purposely.  Let's forge ahead with the data we have through the XML files.
* same as the last point
* same as the last point
* I'm not sure how we'd model this all under a `molecular activity` in a way that would be accessible to BTE/Translator.  And again, this is also dependent on having reaction info in a structured, downloadable file?  So this extension of the parser is also a moot point unless we solve that?  

@NikkiBytes for now, go ahead and move forward after making the changes described in the first two bullet points above.

**Comment by NikkiBytes** [comment]
Example of the newly edited structure, was able to pull the `protein_type`,  and added the alternative IDs. 
Integrating into an API now. 
 
```
[
    {
        "_id": "HMDBP00001_1",
        "pmid": "11752352",
        "subject": {
            "protein_type": "Unknown",
            "uniprot_id": "P21589",
            "uniprot_name": "5NTD_HUMAN",
            "genbank_protein_id": "23897",
            "hgnc_id": "HGNC:8021",
            "genbank_gene_id": "X55740",
            "gene_name": "NT5E"
        },
        "object": {
            "name": "Pentoxifylline",
            "accession": "HMDB0014944",
            "kegg_id": "C01092",
            "chemspider_id": "4578",
            "chebi_id": "127029",
            "pubchem_compound_id": "4740"
        }
    },
    {
        "_id": "HMDBP00001_2",
        "pmid": "16426349",
        "subject": {
            "protein_type": "Unknown",
            "uniprot_id": "P21589",
            "uniprot_name": "5NTD_HUMAN",
            "genbank_protein_id": "23897",
            "hgnc_id": "HGNC:8021",
            "genbank_gene_id": "X55740",
            "gene_name": "NT5E"
        },
        "object": {
            "name": "Pentoxifylline",
            "accession": "HMDB0014944",
            "kegg_id": "C01092",
            "chemspider_id": "4578",
            "chebi_id": "127029",
            "pubchem_compound_id": "4740"
        }
    },
.
.
.
.
]
```

**Comment by colleenXu** [comment]
@NikkiBytes please follow up with @zcqian . I am not involved in the process of actually uploading / creating APIs...

**Comment by NikkiBytes** [comment]
A few notes/updates on the parser.....

- Fixed ERROR `BAD CRC-32`: The input metabolite file, `hmdb_metabolites.xml` from [HMDB downloads](https://hmdb.ca/downloads), the files current version 5.0 is corrupt and produces the error. Version 4.0 works and is being used at the moment, _we will want to look back on this later._.   

- Structure still the same, as an association-centric style document.  

- Adding mapping file, testing on Biothings studio and forking to pending api 

Document Structure Example  
```
[
    {
        "_id": "HMDBP00001_1",
        "pmid": "11752352",
        "subject": {
            "protein_type": "Unknown",
            "uniprot_id": "P21589",
            "uniprot_name": "5NTD_HUMAN",
            "genbank_protein_id": "23897",
            "hgnc_id": "HGNC:8021",
            "genbank_gene_id": "X55740",
            "gene_name": "NT5E"
        },
        "object": {
            "name": "Pentoxifylline",
            "accession": "HMDB0014944",
            "kegg_id": "C07424",
            "chemspider_id": "4578",
            "chebi_id": "127029",
            "pubchem_compound_id": "4740"
        }
    },
    .
    .
    .
]
```

**Comment by andrewsu** [comment]
Looking at the thread above, looks like this data plugin is ready for deployment as a pending API...  Assigning to @erikyao to evaluate...

**Comment by erikyao** [comment]
API published, https://biothings.ncats.io/hmdb

**Comment by colleenXu** [comment]
Related infores stuff is ready:
* new infores catalog entry for BioThings HMDB in PR https://github.com/biolink/biolink-model/pull/1429. However, this is **probably not important** because it isn't the primary infores
* updated infores page for [HMDB (primary knowledge source)](https://github.com/NCATSTranslator/Translator-All/wiki/HMDB)
* added a [placeholder infores page for BioThings HMDB](https://github.com/NCATSTranslator/Translator-All/wiki/BioThings-HMDB-API)

**Comment by colleenXu** [comment]
Going to close this issue and open another one for the SmartAPI yaml w/ x-bte annotation writing
