### ISSUE TITLE
import orthology data from AGR

### ISSUE THREAD

**Issue by andrewsu** [biothings/mygene.info#113]
The Alliance of Genome Resources (AGR) is a consortium of the most highly-used model organisms (mouse, rat, worm, fly, zebrafish, yeast), and they have released their own set of ortholog assignments at https://www.alliancegenome.org/downloads#orthology.  Currently we have homologene in mygene.info, but I think this AGR set would be considered much more reliable for the organisms listed.

**Comment by zcqian** [comment]
Hi @NikkiBytes 
Can you add metadata to the plugin so that it correctly reports the origin and license of the data?

You can see how it's done [here](https://github.com/biothings/mygene.info/blob/master/src/plugins/pantherdb/manifest.json) and [here](https://github.com/biothings/mydisease.info/blob/master/src/plugins/disgenet/manifest.json)

**Comment by zcqian** [comment]
@NikkiBytes I see that you modified `setup_release` in `parser.py` as well. Is this change also intended?

**Comment by zcqian** [comment]
@NikkiBytes I assume you're done making the changes at https://github.com/NikkiBytes/orthologyAGR ? If so I will merge the changes

**Comment by newgene** [comment]
added @jal347 to work with @NikkiBytes on the deployment on mygene.info API.
