### ISSUE TITLE
Some uniprot.Swiss-Prot are not available

### ISSUE THREAD

**Issue by leexgh** [biothings/mygene.info#141]
Uniprot.Swiss-Prot for some genes are not available after the recent [update](https://github.com/biothings/mygene.info/issues/140). For example gene `AR`(entrez ID 367) doesn't have uniprot information anymore https://mygene.info/v3/gene/367?fields=uniprot, it should return P10275 in the response.
This is the link to uniprot: https://www.uniprot.org/uniprotkb/P10275/entry

**Comment by newgene** [comment]
@leexgh we checked, the root cause here is UniProt no longer provides the mapping from `P10275` to NCBIGene `367` any more. Not sure if that's intended or an issue on their end.

You can see the difference from these two records:

https://www.uniprot.org/uniprotkb/P24941/entry  (contains "GeneID: 1017", also linked to NCBI Gene page)

v.s.

https://www.uniprot.org/uniprotkb/P10275/entry (does not contains "GeneID: 367" any more)
