### ISSUE TITLE
"No API definition provided." on https://mygene.info/v3/api

### ISSUE THREAD

**Issue by buchanae** [biothings/mygene.info#43]
<img width="1386" alt="screen shot 2018-07-19 at 10 00 26 am" src="https://user-images.githubusercontent.com/262647/42958567-b5405906-8b3a-11e8-887b-747228f467ac.png">

**Comment by newgene** [comment]
@buchanae Thanks for reporting this. The API metadata for mygene.info is hosted on http://smart-api.info, and it does not support https yet. When you access mygene.info via https, the browser blocks the "unsecure" content served from smart-api.info. The workaround right now is just to use the http://mygene.info. There is a ticket for smartapi to enable its https support: https://github.com/SmartAPI/smartAPI/issues/22.

**Comment by newgene** [comment]
SmartAPI/smartAPI#22 is now fixed. https://mygene.info/v3/api should work now. 

However with on caveat: when under https://mygene.info/v3/api page, users need to switch to "https://mygene.info/v3"  in order to make test queries. This is due to the browser restriction of not allowing mixed https and http content. We will see if possible to set the default automatically
