### ISSUE TITLE
Is ENSMUSG00000068240 correct?

### ISSUE THREAD

**Issue by yjiangnan** [biothings/mygene.info#62]
This is the data I get from MyGeneInfo:
```
{'_id': '22186',
  '_score': 15.649805,
  'entrezgene': '22186',
  'name': 'ubiquitin A-52 residue ribosomal protein fusion product 1',
  'query': 'ENSMUSG00000068240',
  'symbol': 'Uba52',
  'taxid': 10090}
```
But google search shows that ENSMUSG00000068240 is gene Gm11808. While Uba52 corresponds to a different transcript ENSMUSG00000090137.

**Comment by sirloon** [comment]
Ensembl data is coming BioMart, here's the query we use, filtered for these 2 genes:

http://uswest.ensembl.org/biomart/martview/e8e9ec1583e197d4b6787788f5884eeb?VIRTUALSCHEMANAME=default&ATTRIBUTES=mmusculus_gene_ensembl.default.feature_page.ensembl_gene_id%7Cmmusculus_gene_ensembl.default.feature_page.entrezgene&FILTERS=mmusculus_gene_ensembl.default.filters.ensembl_gene_id.%22ENSMUSG00000068240,ENSMUSG00000090137%22&VISIBLEPANEL=resultspanel

(click on "results")

You'll see both are linked to NCBI gene 22186, that's why you see that in mygene. Ensembl website is inconsistent with this:

http://uswest.ensembl.org/Mus_musculus/Gene/Summary?db=core;g=ENSMUSG00000090137;r=8:70508263-70510801 shows that link to NCBI 22186

but not this link: http://uswest.ensembl.org/Mus_musculus/Gene/Summary?db=core;g=ENSMUSG00000068240;r=4:3973092-3973595;t=ENSMUST00000089430

I'm not sure why they have this inconsistency but sometimes there are errors like that...

HTH
