### ISSUE TITLE
Missing exon information in query endpoint

### ISSUE THREAD

**Issue by StephanDecker** [biothings/mygene.info#83]
I would like to get all genes (with their exons) in range by a given chromosomal  position. In general it's possible with your API but there is a bug. Only the exons of the first gene are returned, e.g.:
https://mygene.info/v3/query?q=chr3%3A46411633-46417697&entrezonly=true&fields=exons,symbol  
Could you fix it? Would be great!

**Comment by StephanDecker** [comment]
![image](https://user-images.githubusercontent.com/32638464/82829628-00074600-9eb4-11ea-8e02-b53183841c0c.png)

**Comment by kevinxin90** [comment]
This is not a bug of the API. You can verify using a longer genome range: https://mygene.info/v3/query?q=chr3%3A46411633-46487697&entrezonly=true&fields=exons,symbol&size=100. If you take a look at annotation for this gene (second in your list): http://mygene.info/v3/gene/499800. It doesn't have annotation for exons.

The exon data of MyGene.info is retrieved from UCSC database. The case here is because UCSC doesn't provide annotation for this gene.

And FYI, MyGene.info contains gene annotation for all species. The query you make also returns hits for genes coming from all species. And all genes in your returned list are non-human genes except the first one. If you are only interested in human gene, pass "species=human" as an additional parameter.

**Comment by StephanDecker** [comment]
You are right, thanks a lot!
